---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data
  label: Data-test
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
